[project]
name = "mnist-object-detection-generator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "numpy>=2.3.4",
    "opencv-python>=4.11.0.86",
    "tqdm>=4.67.1",
]
